// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsletterAPI.Data.Contexts;

#nullable disable

namespace NewsletterAPI.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20231109162906_add-nationalcode-to-personnel")]
    partial class addnationalcodetopersonnel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NewsletterAPI.Data.Models.Newsletter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsletterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SendDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Newsletter", (string)null);
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.NewsletterStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("NewsletterId")
                        .HasColumnType("int")
                        .HasColumnName("NewsletterID");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int")
                        .HasColumnName("PersonnelID");

                    b.Property<DateTime?>("ReceiveTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("SendStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SendTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("ViewStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Newslett__C8EE2043E96496D3");

                    b.HasIndex("NewsletterId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("NewsletterStatus", (string)null);
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonnelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.NewsletterStatus", b =>
                {
                    b.HasOne("NewsletterAPI.Data.Models.Newsletter", "Newsletter")
                        .WithMany("NewsletterStatuses")
                        .HasForeignKey("NewsletterId")
                        .HasConstraintName("FK__Newslette__Newsl__38996AB5");

                    b.HasOne("NewsletterAPI.Data.Models.Personnel", "Personnel")
                        .WithMany("NewsletterStatuses")
                        .HasForeignKey("PersonnelId")
                        .HasConstraintName("FK__Newslette__Perso__37A5467C");

                    b.Navigation("Newsletter");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.Newsletter", b =>
                {
                    b.Navigation("NewsletterStatuses");
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.Personnel", b =>
                {
                    b.Navigation("NewsletterStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
