// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsletterAPI.Data.Contexts;

#nullable disable

namespace NewsletterAPI.Migrations.NewsDb
{
    [DbContext(typeof(NewsDbContext))]
    partial class NewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NewsletterAPI.Data.Models.Newsletter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Newsletter");
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.SendNewsletterLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("NewsletterId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceiveTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SendStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SendTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ViewStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NewsletterId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("SendNewsletterLogs");
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.SendNewsletterLog", b =>
                {
                    b.HasOne("NewsletterAPI.Data.Models.Newsletter", "Newsletter")
                        .WithMany("NewsletterStatuses")
                        .HasForeignKey("NewsletterId");

                    b.HasOne("NewsletterAPI.Data.Models.Personnel", "Personnel")
                        .WithMany("NewsletterStatuses")
                        .HasForeignKey("PersonnelId");

                    b.Navigation("Newsletter");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.Newsletter", b =>
                {
                    b.Navigation("NewsletterStatuses");
                });

            modelBuilder.Entity("NewsletterAPI.Data.Models.Personnel", b =>
                {
                    b.Navigation("NewsletterStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
